"""add_user_id_to_tenants

Revision ID: fd821988c15c
Revises: 0007
Create Date: 2026-04-10 15:46:37.087612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd821988c15c'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_constraint('tenants_user_id_fkey', 'tenants', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tenants_user_id_fkey', 'tenants', 'users', ['user_id'], ['id'], referent_schema='auth')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    # ### end Alembic commands ###
